### ISSUE TITLE
Oh Found one bug in hogfather

### ISSUE THREAD

**Issue by bradgillap** [MarcosBL/dokuwiki-plugin-autotabber#4]
Oh I'm sorry I spoke to sooner than I should have. It's not a dealbreaker however. 

While on the DW Editor box. If you createa  list item and use a carriage return (enter) for the next list item. You get 2 carriage returns which drops you below your list.  I've been editing all day on my orgs wiki and haven't noticed any other issues.

So if your list is like here
```
- item 1
- item2 (and you hit enter here)
- (this line is blank except the - because doku knows you're going to add another item to the list )
and this next line is where you cursor ends up.
```

I'm positive it has something to do addition or subtractions with \n newline in the taboverride.js but I haven't quite figured it out.

**Comment by MarcosBL** [comment]
Sorry to hear that, as I no longer even have a Dokuwiki installation, can't test myself, if you figure out a solution, I'll be happy to merge

**Comment by myfirstnameispaul** [comment]
Same problem for automatic indent (e.g., indentation for code blocks).
